language: ruby
rvm:
 - 2.3

services:
 - elasticsearch
before_script:
 - sleep 10
script:
 - bundle exec rake db:setup
 - bundle exec cucumber features

# Set up and start Faye Server before tests are run
before_script:
  - cp test/travis/sync.yml config/sync.yml
  - cp test/travis/sync.ru sync.ru
  - thin start -R sync.ru -p 9292 -t 1 2>&1 > test.log &