# Faye
# development:
#   server: "http://localhost:9292/faye"
#   adapter_javascript_url: "http://localhost:9292/faye/faye.js"
#   auth_token: DEVELOPMENT_SECRET_TOKEN
#   adapter: "Faye"
#   async: true

# Pusher
development:
  adapter_javascript_url: "https://js.pusher.com/4.1/pusher.min.js"
  app_id: "439934"
  api_key: "f44531a8bf307e396700"
  auth_token: "50e4ac464b9df7541b3a"
  adapter: "Pusher"
  async: true

# Disabled
# development:
#   adapter: false

test:
  adapter_javascript_url: "https://js.pusher.com/4.1/pusher.min.js"
  app_id: "439934"
  api_key: "f44531a8bf307e396700"
  auth_token: "50e4ac464b9df7541b3a"
  adapter: "Pusher"
  async: true
# test:
#   server: "http://localhost:9292/faye"
#   adapter_javascript_url: "http://localhost:9292/faye/faye.js"
#   adapter: "Faye"
#   auth_token: "secret"
#   async: false

production:
  development:
  adapter_javascript_url: "https://js.pusher.com/4.1/pusher.min.js"
  app_id: "439934"
  api_key: "f44531a8bf307e396700"
  auth_token: "50e4ac464b9df7541b3a"
  adapter: "Pusher"
  async: true
